trigger:
  branches:
    include:
      - master
  paths:
    include:
      - martian-robots

pool:
  vmImage: 'windows-latest'

steps:
- task: spontoreau.rust-vsts.rust-install.Rust@1
  displayName: Install

- task: spontoreau.rust-vsts.rust-cargo.Cargo@1
  displayName: Build
  inputs:
    cargoCommand: build
    cargoWorkingDir: 'martian-robots'

- task: CopyFiles@2
  displayName: 'Copy exe'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/martian-robots/target/debug'
    Contents: 'martian-robots.exe'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  displayName: 'Copy wwwroot'
  inputs:
    SourceFolder: 'martian-robots/wwwroot'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish
