trigger:
- master/martian-robots

pool:
  vmImage: 'windows-latest'

steps:
- task: spontoreau.rust-vsts.rust-install.Rust@1
  displayName: Install

- task: spontoreau.rust-vsts.rust-cargo.Cargo@1
  displayName: Build
  inputs:
    cargoCommand: build
    cargoWorkingDir: 'martian-robots'

- task: CopyFiles@2
  displayName: 'Copy exe'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/martian-robots/target/debug'
    Contents: 'martian-robots.exe'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  displayName: 'Copy wwwroot'
  inputs:
    SourceFolder: 'martian-robots/wwwroot'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: Publish

- task: ArchiveFiles@2
  displayName: Zip
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
    includeRootFolder: false
    archiveFile: '$(Build.ArtifactStagingDirectory)/drop.zip'
  enabled: false

- task: AzureRmWebAppDeployment@4
  displayName: Deploy
  inputs:
    azureSubscription: 'Pay-As-You-Go (d40c53cc-9981-4d98-a471-35df02d0bdc7)'
    WebAppName: 'martian-robots'
    VirtualApplication: /rust
    packageForLinux: '$(Build.ArtifactStagingDirectory)/drop.zip'
  enabled: false
